# worker_processes  1;

# events {
#     worker_connections  1024;
# }

# http {
#     include       mime.types;
#     default_type  application/octet-stream; 

#     sendfile        on;
#     keepalive_timeout  65;

#     # 1. הקמת אזור זיכרון משותף יחיד בשם my_limit
#     limit_conn_by_header_zone $http_x_api_key zone=my_limit:10m;

#     server {
#         listen       80;
#         server_name  localhost;

#         location / {
#             root   /home/ser/nginx/docs/html;
#             index  index.html index.htm;

#             # 2. אכיפת המגבלה: מותר רק חיבור בו-זמני אחד (1) לכל מפתח!
#             limit_conn_by_header my_limit 2; 
#             limit_conn_header_status_code 503;
#         }

#         error_page   500 502 503 504  /50x.html;
#         location = /50x.html {
#             root   html;
#         }
#     }
# }

worker_processes  1;

events {
    worker_connections  1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;

    # כאן מגדירים את ה-Zone ברמת ה-HTTP
    limit_conn_by_header_zone $http_x_api_key zone=my_limit:10m;

    server {
        listen       80;
        server_name  localhost;

        location / {
            root   /home/ser/nginx/docs/html;
            index  index.html index.htm;

            # אכיפת המגבלה בתוך ה-Location
            limit_conn_by_header my_limit 2; 
            limit_conn_header_status_code 503;
        }
    }
}